generators:
- sno-ran-du/sno-ran-du-pg-v1.yaml
# This ACM PG is needed when the previous one has to be updated.
- sno-ran-du/sno-ran-du-pg-v2.yaml


resources:
- sno-ran-du/ns.yaml
- sno-ran-du/msc-binding.yaml
