apiVersion: v1
kind: ConfigMap
metadata:
  name: dell-intel-cu-template-configmap-v1
  namespace: oran-o2ims
data:
  # hardwareProvisioningTimeout is optional.
  # The value should be a duration string
  # (e.g., "60m" for 60 minutes)
  hardwareProvisioningTimeout: "60m"
  hwMgrId: dell-hwmgr
  bootInterfaceLabel: bootable-interface
  node-pools-data: |
    - name: master
      hwProfile: profile-spr-single-processor-64G
    - name: worker
      hwProfile: profile-spr-dual-processor-128G
